apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/sebian-lab/alphatracer-financial-api
  newName: ghcr.io/sebian-lab/alphatracer-financial-api
  newTag: 29660e11b60d76b91f3a23721d5a310feba6c1cc
