apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/sebian-lab/alphatracer-financial-api
    newTag: d83d9d9dd4485358e07c67d934103bf129697cea  # updated by CI
