apiVersion: apps/v1
kind: Deployment
metadata:
  name: alphatracer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alphatracer
  template:
    metadata:
      labels:
        app: alphatracer
    spec:
      containers:
      - name: api
        image: ghcr.io/sebian-lab/alphatracer-financial-api:latest   # overwritten by Kustomize
        ports:
        - containerPort: 8011
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: alphatracer-secrets
              key: database-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: alphatracer-secrets
              key: secret-key
        - name: ALGORITHM
          value: "HS256"
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: "60"
        - name: PRIMARY_TICKER_CSV
          value: "https://raw.githubusercontent.com/abbadata/stock-tickers/main/data/all.csv"
        - name: SECONDARY_TICKER_CSV
          value: "https://raw.githubusercontent.com/Ate329/top-us-stock-tickers/main/tickers/all.csv"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
