apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alphatracer-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: alphatracer
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
