apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/sebian-lab/alphatracer-financial-api
  newName: ghcr.io/sebian-lab/alphatracer-financial-api
  newTag: 89a88aac545c6c7863613ff47b13199b79ce1a18
