apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/sebian-lab/alphatracer-financial-api
  newName: ghcr.io/sebian-lab/alphatracer-financial-api
  newTag: 28b69dd1553183be471875c8c06d2277adb90c04
