apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alphatracer-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sebian-lab/alphatracer-financial-api
    targetRevision: dev
    path: infrastructure/kubernetes/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: alphatracer-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
